name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # To run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote 
        env:
          HF: ${{ secrets.HF }}
        run: git remote add space https://mahad049:$HF@huggingface.co/spaces/mahad049/huggingface_deploy
      - name: Push to hub
        env:
          HF: ${{ secrets.HF }}
        run: git push --force https://mahad049:$HF@huggingface.co/spaces/mahad049/huggingface_deploy main
